import os


# Common.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Telegram Bot API.
TELEGRAM_BOT_TOKEN = 'set in local settings'


# DialogFlow API settings.

# Path to private key settings generated by google cloud.
PRIVATE_KEY_PATH = 'set in local settings'

DIALOGFLOW_PROJECT_ID = 'set in local settings'

# Default language code, override in local_settings.py if it is necessary.
DIALOGFLOW_LANGUAGE_CODE = 'en-US'

# Dev token.
DIALOGFLOW_DEV_TOKEN = 'set in local settings'


# CoinMarketCap API.
X_CMC_PRO_API_KEY = 'set in local settings'

X_CMC_PRO_API_QUOTES_LATEST_URL = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?'


try:
	from app.local_settings import *
except ImportError:
	pass


# CoinMarketCap API setup.
X_CMC_PRO_API_HEADERS = {
	'Accept': 'application/json',
	'Accept-Encoding': 'deflate, gzip',
	'X-CMC_PRO_API_KEY': X_CMC_PRO_API_KEY,
}


# DialogFlow API settings setup.
assert os.path.exists(PRIVATE_KEY_PATH)
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = PRIVATE_KEY_PATH
